# используем язык java. Travis CI поддерживает другие языки тоже.
env:
  global:
    - CODECOV_TOKEN="18ee38b7-428e-4be0-87f9-4684760bdf2d"
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту geohound90@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - geohound90@gmail.com
    on_success: never # default: change
    on_failure: always # default: always